### PR TITLE
Windows Phone 8.1 Support

### PR DESCRIPTION
**Pull request by AndrewAtAvenza**
I've been using this for a couple of days in the development of our Windows Phone 8.1 app and it seems to work there. Though in this case I've integrated them in such a way as to not break the 8.0 Silverlight build (currently in our project I don't have #if-defs, just flat out changed to 8.1). So its not quite the same, but it should be equivalent. Everything is pretty much in something like:

#if WINDOWS_PHONE_APP
// WP8.1 version
#else
// old code
#endif

With the exception of a few spots where there was no #else clause. I have two spots I'm not super happy, and I've marked them with 

/// @todo 

to make them easy to find. I just haven't found good analogs yet in the WP8.1 API.

The WP8.1 support is in the first commit; the next two are corrections to get the test & samples to compile. I started to try and get a copy of the sample & tests for Windows Phone 8.1 working but it's going to take longer than I have today to finish :) If you're interested in this set of changes, I'll take a stab at adding a working WP8.1 sample & test suite. I'm pretty sure its quite doable, it's just time consuming because of the all the #if-defing.

### CODE REVIEW

**Comment by damieng** [comment]
Generally there is a bit of discussion around a pull request and the person who wrote the new code makes a few tweaks to their branch. 

I'd go with putting 81 after WindowsPhone.

Thanks!

**Comment by AndrewAtAvenza** [comment]
Okay, I reverted my initial commit of WP8.1 changes and redid them as suggested. Then I renamed the files as I just pushed my first guess at the naming convention -- fortunately there are no class renames involved so it was very straightforward :)

I also just gave it a quick test in my app and everything builds & I can see the screen hits showing up in GA so I guess its still working!

I've pushed the changes, do I need to re-issue a pull request? I clicked on 'New Pull Request' and it just seemed to dump me back here, so I'm guessing no.

**Comment by damieng** [comment]
That looks like it's updated the pull request (I use the Files changed tab at the top of GitHub to see the final changes).  It looks like the new classes though don't have 81 in the class name?

I should be able to take a look at this tonight (about 12 hours) and merge it in.

**Comment by AndrewAtAvenza** [comment]
I'm not sure why they wouldn't my second set had files ending with .WP81.cs but I pushed another change that moved changed that back to just .cs & added 81 after 'WIndowsPhone' as you suggested. I see that change in the list above on this page, so hopefully that is included in the pull request!

**Pull request merged**
